### ISSUE TITLE
System.NullReferenceException in CssTools.CssExtensions.GetDeclarations

### ISSUE THREAD

**Issue by Allann** [madskristensen/CssTools#11]
### Installed product versions
- Visual Studio: 2017 15.8.0 Preview 4
- This extension:  CssTools 1.1.21

### Description
When using the normal VS Find/Replace feature, when clicking the Replace single and Find Next button on the widget, VS crashes after a few seconds of inactivity.

### Steps to recreate
1. Open a project with multiple files
2. Open a code editor, select some text
3. Press Ctrl+H to display find replace dialog and enter some replace text
4. Press the Replace and Find Next button

### Current behavior
VS2017 crashes with the following exception in the activity log:
```xml
  <entry>
    <record>2825</record>
    <time>2018/07/12 23:15:41.627</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at CssTools.CssExtensions.GetDeclarations(RuleBlock rule) in C:\projects\csstools\src\ExtensionMethods\CssExtensions.cs:line 45&#x000D;&#x000A;   at CssTools.VendorClassifier.UpdateDeclarationCache(ParseItem item) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 116&#x000D;&#x000A;   at CssTools.VendorClassifier..ctor(IClassificationTypeRegistryService registry, ITextBuffer buffer) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 59&#x000D;&#x000A;   at CssTools.VendorClassifierProvider.&lt;&gt;c__DisplayClass4_0.&lt;GetClassifier&gt;b__0() in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 37&#x000D;&#x000A;   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)&#x000D;&#x000A;   at CssTools.VendorClassifierProvider.GetClassifier(ITextBuffer textBuffer) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 37&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTaggerProvider.&lt;&gt;c__DisplayClass12_0`1.&lt;CreateTagger&gt;b__0(IClassifierProvider provider)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeEligibleFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, IContentTypeRegistryService contentTypeRegistryService, Object errorSource)</description>
  </entry>

```

### Expected behavior
normal Find and Replace functionality.

**Comment by AccessIT** [comment]
I also get the same error when opening an ASPX page in source view

System.NullReferenceException: Object reference not set to an instance of an object.   at CssTools.CssExtensions.GetDeclarations(RuleBlock rule) in C:\projects\csstools\src\ExtensionMethods\CssExtensions.cs:line 45   at CssTools.VendorClassifier.UpdateDeclarationCache(ParseItem item) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 116   at CssTools.VendorClassifier..ctor(IClassificationTypeRegistryService registry, ITextBuffer buffer) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 59   at CssTools.VendorClassifierProvider.<>c__DisplayClass4_0.<GetClassifier>b__0() in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 37   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)   at CssTools.VendorClassifierProvider.GetClassifier(ITextBuffer textBuffer) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 37   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTaggerProvider.<>c__DisplayClass12_0`1.<CreateTagger>b__0(IClassifierProvider provider)   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeEligibleFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, IContentTypeRegistryService contentTypeRegistryService, Object errorSource
--

**Comment by smabuk** [comment]
I get the same when I open any Razor page with some styles specified or in scss files.

Currently using VS 15.8 preview 5, but I've seen it in earlier versions as well.

```
  <entry>
    <record>1333</record>
    <time>2018/08/08 15:46:57.589</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at CssTools.CssExtensions.GetDeclarations(RuleBlock rule) in C:\projects\csstools\src\ExtensionMethods\CssExtensions.cs:line 45&#x000D;&#x000A;   at CssTools.VendorClassifier.UpdateDeclarationCache(ParseItem item) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 116&#x000D;&#x000A;   at CssTools.VendorClassifier..ctor(IClassificationTypeRegistryService registry, ITextBuffer buffer) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 59&#x000D;&#x000A;   at CssTools.VendorClassifierProvider.&lt;&gt;c__DisplayClass4_0.&lt;GetClassifier&gt;b__0() in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 37&#x000D;&#x000A;   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)&#x000D;&#x000A;   at CssTools.VendorClassifierProvider.GetClassifier(ITextBuffer textBuffer) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 37&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTaggerProvider.&lt;&gt;c__DisplayClass12_0`1.&lt;CreateTagger&gt;b__0(IClassifierProvider provider)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeEligibleFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, IContentTypeRegistryService contentTypeRegistryService, Object errorSource)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>
```

**Comment by waldev** [comment]
I'm receiving the same error when opening a Razor page.

Using VS Pro 15.8.0.

`<entry>
    <record>1028</record>
    <time>2018/08/14 22:12:38.288</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at CssTools.CssExtensions.GetDeclarations(RuleBlock rule) in C:\projects\csstools\src\ExtensionMethods\CssExtensions.cs:line 45&#x000D;&#x000A;   at CssTools.VendorClassifier.UpdateDeclarationCache(ParseItem item) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 116&#x000D;&#x000A;   at CssTools.VendorClassifier..ctor(IClassificationTypeRegistryService registry, ITextBuffer buffer) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 59&#x000D;&#x000A;   at CssTools.VendorClassifierProvider.&lt;&gt;c__DisplayClass4_0.&lt;GetClassifier&gt;b__0() in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 37&#x000D;&#x000A;   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)&#x000D;&#x000A;   at CssTools.VendorClassifierProvider.GetClassifier(ITextBuffer textBuffer) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 37&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTaggerProvider.&lt;&gt;c__DisplayClass12_0`1.&lt;CreateTagger&gt;b__0(IClassifierProvider provider)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeEligibleFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, IContentTypeRegistryService contentTypeRegistryService, Object errorSource)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>`

**Comment by MarkSky** [comment]
I Update Visual Stuido to the version 15.8 today, and when I open css or scss files, I got the same error.

**Comment by acmieremet** [comment]
same here opening a cshtml in visual studio v 15.8.0 throws error


> | System.NullReferenceException: Object reference not set to an instance of an object.   at
>  CssTools.CssExtensions.GetDeclarations(RuleBlock rule) in
>  C:\projects\csstools\src\ExtensionMethods\CssExtensions.cs:line 45   at 
>  CssTools.VendorClassifier.UpdateDeclarationCache(ParseItem item) in 
>  C:\projects\csstools\src\Classify\VendorClassifier.cs:line 116   at 
>  CssTools.VendorClassifier..ctor(IClassificationTypeRegistryService registry, ITextBuffer buffer) in 
>  C:\projects\csstools\src\Classify\VendorClassifier.cs:line 59   at CssTools.VendorClassifierProvider 
>  .<>c__DisplayClass4_0.<GetClassifier>b__0() in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 
>  37   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, 
>  Func`1 creator)   at CssTools.VendorClassifierProvider.GetClassifier(ITextBuffer textBuffer) in 
>  C:\projects\csstools\src\Classify\VendorClassifier.cs:line 37   at 
>  Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTaggerProvider. <>c__DisplayClass12_0`1.<CreateTagger>b__0(IClassifierProvider provider)   at  Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeEligibleFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, IContentTypeRegistryService contentTypeRegistryService, Object errorSource) --- End of stack trace from previous location where exception was thrown ---   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
> -- | --
>

**Comment by CSchuster** [comment]
same here with VS 2017 15.8

**Comment by wgutierrezr** [comment]
The same for me using VS 2017 15.8

**Comment by BrotherErryn** [comment]
Same here with the 4.7.02556 build,

**Comment by gerardogup** [comment]
Same problem here after update to VS 2017 15.8
