### ISSUE TITLE
Visual Studio 2019 support

### ISSUE THREAD

**Issue by stamminator** [madskristensen/CssTools#18]
### Installed product versions
- Visual Studio: Visual Studio 2019 RC.2

### Description
Provide extension support for Visual Studio 2019

**Comment by madskristensen** [comment]
Does this not install? http://vsixgallery.com/extension/1c63270f-485d-4810-99b8-e9d9de82610c/

**Comment by stamminator** [comment]
That did the trick, thanks. I've never heard of vsixgallery.com before. How is this different from marketplace.visualstudio.com?

**Comment by madskristensen** [comment]
It's a staging ground for CI and nightly builds before. Marketplace is still where it's at and I'll upload this one when I finish doing some more testing
