### ISSUE TITLE
Exception thrown in Visaul Studio 2017.4.1

### ISSUE THREAD

**Issue by AccessIT** [madskristensen/CssTools#5]
### Installed product versions
- Visual Studio: 2017.4.1 Enterprise
- This extension: 1.1.20

### Description
When viewing a web form page (aspx.cs) in source view a exception as recorded in the ActivityLog.xml

### Steps to recreate
Using an existing web application (Web Forms) under .NET 4.0
When I switch to a aspx.cs tab a message to check the ActivityLog.xml is displayed.
It contains the stack trace below.
The page displays but the CSS tools is disabled

**NOTE:** Virtually all pages in the site are "Web forms with master page" which might be significant

### Current behavior
Exception generated viewing aspx.cs page

Stack trace from ActivityLog.xml

  | System.MissingMethodException: Method not found: 'System.Collections.Generic.IReadOnlyList`1<Microsoft.CSS.Core.TreeItems.Declaration> Microsoft.CSS.Core.TreeItems.RuleBlock.get_Declarations()'.   at CssTools.VendorClassifier.UpdateDeclarationCache(ParseItem item)   at CssTools.VendorClassifier..ctor(IClassificationTypeRegistryService registry, ITextBuffer buffer) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 59   at CssTools.VendorClassifierProvider.<>c__DisplayClass4_0.<GetClassifier>b__0() in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 37   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)   at CssTools.VendorClassifierProvider.GetClassifier(ITextBuffer textBuffer) in C:\projects\csstools\src\Classify\VendorClassifier.cs:line 37   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTaggerProvider.<>c__DisplayClass12_0`1.<CreateTagger>b__0(IClassifierProvider provider)   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeEligibleFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, IContentTypeRegistryService contentTypeRegistryService, Object errorSource) --- End of stack trace from previous location where exception was thrown ---    at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
-- | --

### Expected behaviour
Currently cannot use CSS tools in aspx pages

**Comment by madskristensen** [comment]
Fixed
